/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/B3Bb8HErROz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage } from "@/components/ui/avatar"

export default function Component() {
  return (
    <div>
      <header className="flex flex-col gap-x-3 lg:flex-row items-center justify-between py-12 px-8 bg-gray-100" style={{height: '95vh'}}>
        <div className="lg:w-1/2 space-y-6">
          <h2 className="text-4xl font-bold leading-tight">Embark on a magical bedtime story quest</h2>
          <p className="text-lg ">
            Create enchanting bedtime stories tailored to your child's name, favorite characters, and themes, and have
            AI narrate them on your epic journey!
          </p>
          <div className="flex space-x-4">
            <Button>Start your adventure</Button>
            <Button variant="secondary" className="bg-indigo-400 hover:bg-indigo-500 text-white">
              <Link href="/">
                Try the demo
              </Link>
            </Button>
          </div>
          <div className="flex items-center space-x-2">
            <div className="flex -space-x-2">
              <Avatar>
                <AvatarImage src="/users.png" />
              </Avatar>
              <Avatar>
                <AvatarImage src="/users.png" />
              </Avatar>
              <Avatar>
                <AvatarImage src="/users.png" />
              </Avatar>
              <Avatar>
                <AvatarImage src="/users.png" />
              </Avatar>
              <Avatar>
                <AvatarImage src="/users.png" />
              </Avatar>
            </div>
            <p className="text-sm ">
              <TrophyIcon className="text-indigo-400 w-4 h-4" /> Joined by 1,000+ adventurers!
            </p>
          </div>
        </div>
        <div className="lg:w-1/2 mt-12 lg:mt-0">
          <img src="/story-telling.jpeg" alt="AI creating stories" className="max-w-full h-auto rounded" />
        </div>
      </header> 
      <main>
        <section className="py-12 px-8">
          <div className="max-w-3xl mx-auto space-y-6">
            <h2 className="text-3xl font-bold">Level up your storytelling</h2>
            <p className="">Unlock new realms of adventure with our game-like progression system.</p>
          </div>
          <div className="max-w-3xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
            <div className="border  border-gray-600 p-6 rounded-lg">
              <h3 className="text-xl font-bold mb-4">Novice Adventurer</h3>
              <ul className="space-y-2 ">
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  2 short stories
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  Unlimited voice narrations
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  1 voice actor
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  Email support
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  Supported languages: English
                </li>
              </ul>
              <div className="mt-6">
                <span className="text-3xl font-bold">Free</span>
                <span className=" ml-2">to start</span>
              </div>
              <Button className="mt-4 bg-indigo-400 hover:bg-indigo-500">Begin your quest</Button>
            </div>
            <div className="border border-gray-600 p-6 rounded-lg">
              <h3 className="text-xl font-bold mb-4">Master Storyteller</h3>
              <ul className="space-y-2 ">
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  30 short, medium, or long stories
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  Unlimited voice narrations
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  5 unique voice actors
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  Priority support
                </li>
                <li className="flex items-center">
                  <CheckIcon className="w-4 h-4 mr-2 text-indigo-400" />
                  Supported languages: English, Chinese, French, German, Italian, Japanese, Korean, Spanish
                </li>
              </ul>
              <div className="mt-6">
                <span className="text-3xl font-bold">$9</span>
                <span className=" ml-2">Billed Monthly</span>
              </div>
              <Button className="mt-4 bg-indigo-400 hover:bg-indigo-500">Unlock this tier</Button>
            </div>
          </div>
        </section>
      </main>
      {/* <footer className="border text-white py-12 px-8">
        <div className="max-w-3xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div>
            <h1 className="text-2xl font-bold mb-4">Sleepytales Adventure</h1>
            <p className="">
              Transform bedtime stories into a magical adventure with our AI bedtime story generator.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-4">Twitter</h3>
            <ul className="space-y-2 ">
              <li>
                <Link href="#" prefetch={false}>
                  Follow us on Twitter
                </Link>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-4">Support</h3>
            <ul className="space-y-2 ">
              <li>
                <Link href="#" prefetch={false}>
                  Contact
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  FAQs
                </Link>
              </li>
            </ul>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-4">Realms</h3>
            <ul className="space-y-2 ">
              <li>
                <Link href="#" prefetch={false}>
                  Fairy Tale Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Pirate's Cove Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Enchanted Forest Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Mythical Creature Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Outer Space Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Medieval Kingdom Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Underwater Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Magical School Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Spooky Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Time Travel Realm
                </Link>
              </li>
              <li>
                <Link href="#" prefetch={false}>
                  Superhero Realm
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </footer> */}
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function TrophyIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>
  )
}
